//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sommer_al.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comings
    {
        public int ComingID { get; set; }
        public int ReceiptID { get; set; }
        public int MaterialID { get; set; }
        public Nullable<decimal> MaterialCount { get; set; }
        public Nullable<decimal> MaterialPricePerUnit { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual ReceiptInvoices ReceiptInvoices { get; set; }
    }
}
