//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sommer_al.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defects
    {
        public int DefectID { get; set; }
        public System.DateTime DefectDate { get; set; }
        public int ModelID { get; set; }
        public Nullable<int> DefectCount { get; set; }
        public string Cause { get; set; }
        public int StatysID { get; set; }
    
        public virtual ShoeModels ShoeModels { get; set; }
        public virtual Statys Statys { get; set; }
    }
}
