//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sommer_al.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departs
    {
        public int DepartID { get; set; }
        public int ExpenseID { get; set; }
        public int ModelID { get; set; }
        public Nullable<int> ShoesCount { get; set; }
    
        public virtual ExpenseInvoices ExpenseInvoices { get; set; }
        public virtual ShoeModels ShoeModels { get; set; }
    }
}
