//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sommer_al.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseInvoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpenseInvoices()
        {
            this.Departs = new HashSet<Departs>();
        }
    
        public int ExpenseID { get; set; }
        public string ExpenseNumber { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public int StoreID { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public int StatysID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departs> Departs { get; set; }
        public virtual Statys Statys { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
