//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sommer_al.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgramModPR5Entities : DbContext
    {
        public ProgramModPR5Entities()
            : base("name=ProgramModPR5Entities")
        {
        }

        private static ProgramModPR5Entities _context;
        public static ProgramModPR5Entities GetContext()
        {
            return new ProgramModPR5Entities();
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Comings> Comings { get; set; }
        public virtual DbSet<Defects> Defects { get; set; }
        public virtual DbSet<Departs> Departs { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Equipments> Equipments { get; set; }
        public virtual DbSet<EquipTypes> EquipTypes { get; set; }
        public virtual DbSet<ExpenseInvoices> ExpenseInvoices { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<ReceiptInvoices> ReceiptInvoices { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Seasons> Seasons { get; set; }
        public virtual DbSet<ShoeModels> ShoeModels { get; set; }
        public virtual DbSet<Statys> Statys { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<TMRequests> TMRequests { get; set; }
        public virtual DbSet<Units> Units { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
