//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sommer_al.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptInvoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceiptInvoices()
        {
            this.Comings = new HashSet<Comings>();
        }
    
        public int ReceiptID { get; set; }
        public string ReceiptNumber { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public int SupplierID { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public int StatysID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comings> Comings { get; set; }
        public virtual Statys Statys { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
