//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sommer_al.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ReviewID { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public int StoreID { get; set; }
        public int ModelID { get; set; }
        public string ReviewDesc { get; set; }
        public int Rating { get; set; }
    
        public virtual ShoeModels ShoeModels { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
