//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sommer_al.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoeModels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoeModels()
        {
            this.Defects = new HashSet<Defects>();
            this.Departs = new HashSet<Departs>();
            this.Reviews = new HashSet<Reviews>();
        }
    
        public int ModelID { get; set; }
        public string ShoeModelName { get; set; }
        public string Article { get; set; }
        public int SeasonID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public string ModelDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defects> Defects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departs> Departs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviews> Reviews { get; set; }
        public virtual Seasons Seasons { get; set; }
    }
}
