//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sommer_al.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMRequests
    {
        public int RequestID { get; set; }
        public int EquipID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string TMRequestDescription { get; set; }
        public int StatysID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Equipments Equipments { get; set; }
        public virtual Statys Statys { get; set; }
    }
}
